# Funding — https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# github: [username]
# ko_fi: username
# custom: ["https://paypal.me/senalabs"]
